# Generated by Django 2.2.13 on 2021-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20201106_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.ManyToManyField(blank=True, to='auctions.Category'),
        ),
    ]
